//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarShopRacingWF.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ValidarUsuario", ReplyAction="http://tempuri.org/IService1/ValidarUsuarioResponse")]
        System.Data.DataSet ValidarUsuario(string Login, string Pasword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ValidarUsuario", ReplyAction="http://tempuri.org/IService1/ValidarUsuarioResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> ValidarUsuarioAsync(string Login, string Pasword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertarUsuario", ReplyAction="http://tempuri.org/IService1/InsertarUsuarioResponse")]
        System.Data.DataSet InsertarUsuario(string Username, string pasword, int Rol, bool Estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertarUsuario", ReplyAction="http://tempuri.org/IService1/InsertarUsuarioResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> InsertarUsuarioAsync(string Username, string pasword, int Rol, bool Estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListarRol", ReplyAction="http://tempuri.org/IService1/ListarRolResponse")]
        System.Data.DataSet ListarRol();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListarRol", ReplyAction="http://tempuri.org/IService1/ListarRolResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> ListarRolAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListarUsuarios", ReplyAction="http://tempuri.org/IService1/ListarUsuariosResponse")]
        System.Data.DataSet ListarUsuarios(int IdUsuario, int IdRol, string Estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListarUsuarios", ReplyAction="http://tempuri.org/IService1/ListarUsuariosResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> ListarUsuariosAsync(int IdUsuario, int IdRol, string Estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EditarUsuario", ReplyAction="http://tempuri.org/IService1/EditarUsuarioResponse")]
        System.Data.DataSet EditarUsuario(int IdUsuario, string Username, string Pasword, int IdRol, bool Estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EditarUsuario", ReplyAction="http://tempuri.org/IService1/EditarUsuarioResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> EditarUsuarioAsync(int IdUsuario, string Username, string Pasword, int IdRol, bool Estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuscarUsuario", ReplyAction="http://tempuri.org/IService1/BuscarUsuarioResponse")]
        System.Data.DataSet BuscarUsuario(int idusuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuscarUsuario", ReplyAction="http://tempuri.org/IService1/BuscarUsuarioResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> BuscarUsuarioAsync(int idusuario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : CarShopRacingWF.ServiceReference2.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<CarShopRacingWF.ServiceReference2.IService1>, CarShopRacingWF.ServiceReference2.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet ValidarUsuario(string Login, string Pasword) {
            return base.Channel.ValidarUsuario(Login, Pasword);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ValidarUsuarioAsync(string Login, string Pasword) {
            return base.Channel.ValidarUsuarioAsync(Login, Pasword);
        }
        
        public System.Data.DataSet InsertarUsuario(string Username, string pasword, int Rol, bool Estado) {
            return base.Channel.InsertarUsuario(Username, pasword, Rol, Estado);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> InsertarUsuarioAsync(string Username, string pasword, int Rol, bool Estado) {
            return base.Channel.InsertarUsuarioAsync(Username, pasword, Rol, Estado);
        }
        
        public System.Data.DataSet ListarRol() {
            return base.Channel.ListarRol();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ListarRolAsync() {
            return base.Channel.ListarRolAsync();
        }
        
        public System.Data.DataSet ListarUsuarios(int IdUsuario, int IdRol, string Estado) {
            return base.Channel.ListarUsuarios(IdUsuario, IdRol, Estado);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ListarUsuariosAsync(int IdUsuario, int IdRol, string Estado) {
            return base.Channel.ListarUsuariosAsync(IdUsuario, IdRol, Estado);
        }
        
        public System.Data.DataSet EditarUsuario(int IdUsuario, string Username, string Pasword, int IdRol, bool Estado) {
            return base.Channel.EditarUsuario(IdUsuario, Username, Pasword, IdRol, Estado);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> EditarUsuarioAsync(int IdUsuario, string Username, string Pasword, int IdRol, bool Estado) {
            return base.Channel.EditarUsuarioAsync(IdUsuario, Username, Pasword, IdRol, Estado);
        }
        
        public System.Data.DataSet BuscarUsuario(int idusuario) {
            return base.Channel.BuscarUsuario(idusuario);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> BuscarUsuarioAsync(int idusuario) {
            return base.Channel.BuscarUsuarioAsync(idusuario);
        }
    }
}
